# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onestock', '0002_auto_20171119_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotels',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
