# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestock', '0003_auto_20171119_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
