# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import onestock.validators


class Migration(migrations.Migration):

    dependencies = [
        ('onestock', '0004_hotels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[onestock.validators.validate_category]),
        ),
    ]
