# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
